import Test.MIR.Helpers
import Test.MIR.ANF.Golden
import Test.MIR.ANF.Unit
import Test.MIR.Opt.Golden
import Test.MIR.Opt.IsPure
import Test.MIR.Opt.ExprStructEq
import Test.MIR.Opt.LookupStructEq
import Test.MIR.Opt.AllUsesAreForce
import Test.MIR.Opt.OccursUnderFix
import Test.MIR.Opt.ShouldInline
import Test.MIR.Opt.FloatOut
import Test.MIR.Opt.CSE
import Test.MIR.Opt.DCE
import Test.MIR.Opt.ForceDelay
import Test.MIR.Opt.InlinePass
import Test.MIR.Opt.Pipeline
import Test.MIR.Lower.Golden
import Test.MIR.Eval.Golden
import Test.MIR.Eval.Compile
import Test.MIR.Eval.Policy
import Test.MIR.Analysis.Unit
import Test.MIR.Suites
