name = "moist"
version = "0.1.0"
defaultTargets = ["moist"]

[[lean_lib]]
name = "Moist"

[[lean_lib]]
name = "Test"

[[lean_exe]]
name = "moist"
root = "Main"

[[lean_exe]]
name = "test-golden"
root = "TestGolden"

[[lean_exe]]
name = "test-opt-golden"
root = "TestOptGolden"

[[lean_exe]]
name = "test-lower-golden"
root = "TestLowerGolden"
