import Moist.SMT.Soundness.Simulation

namespace Moist.SMT.UPLC.Soundness

open Moist.Plutus.Term
open Moist.Verified.BigStep
open Moist.CEK (CekEnv CekValue)

/-! # Integer-equality query endpoint

This module connects `okIntEqCond`, the assertion generated by
`scriptForIntEq`, to the concrete big-step evaluator.  The public CEK-facing
corollary is kept in `Moist.SMT.Soundness`.
-/

theorem okIntEqCond_eval_true_mem {m : SmtSem.Model} {outs : List Outcome}
    {rhs : SExpr}
    (h : SmtSem.evalBoolIs m (okIntEqCond outs rhs) true = true) :
    ∃ pc v,
      Outcome.ok pc v ∈ outs ∧
      pcHolds m pc = true ∧
      pcHolds m (asInt v).guard = true ∧
      pcHolds m (SExpr.eq (asInt v).val rhs) = true := by
  obtain ⟨candidate, hcandidate, htrue⟩ := evalBoolIs_any_true (m := m)
    (xs := outs.filterMap fun
      | .ok pc v =>
          let i := asInt v
          some (SExpr.all [pc, i.guard, SExpr.eq i.val rhs])
      | _ => none)
    (by simpa [okIntEqCond] using h)
  simp only [List.mem_filterMap] at hcandidate
  rcases hcandidate with ⟨out, hout, hmapped⟩
  cases out with
  | error pc => simp at hmapped
  | timeout pc => simp at hmapped
  | ok pc v =>
      simp at hmapped
      subst candidate
      have hparts := pcHolds_all3 (m := m)
        (by simpa [pcHolds] using htrue)
      exact ⟨pc, v, hout, hparts.1, hparts.2.1, hparts.2.2⟩

theorem evalSym_okIntEqCond_bigEval {m : SmtSem.Model} {fuel : Nat}
    {ρ : List SymVal} {env : CekEnv} {t : Term} {rhs : SExpr} {expected : Int}
    (henv : symEnvToCek? m ρ = some env)
    (hρno : symEnvNoOpaqueForSoundness ρ = true)
    (hno : termNoOpaqueBuiltinsForSoundness t)
    (hrhs : SmtSem.eval m rhs = some (.int expected))
    (hcond : SmtSem.evalBoolIs m
      (okIntEqCond (evalSym fuel ρ t) rhs) true = true) :
    bigEval fuel env t = some (.VCon (.Integer expected)) := by
  obtain ⟨pc, v, hmem, hpc, hguard, heq⟩ :=
    okIntEqCond_eval_true_mem hcond
  obtain ⟨cv, hv, _hnov, hbig⟩ := evalSym_path_ok_noOpaque
    (m := m) (fuel := fuel) (ρ := ρ) (env := env) (t := t)
    henv hρno hno hmem hpc
  obtain ⟨actual, rfl, hactual⟩ := asInt_sound hv hguard
  have : actual = expected := pcHolds_eq_int hactual hrhs heq
  subst actual
  exact hbig

theorem evalSym_simplifiedOkIntEqCond_bigEval {m : SmtSem.Model} {fuel : Nat}
    {ρ : List SymVal} {env : CekEnv} {t : Term} {rhs : SExpr} {expected : Int}
    (henv : symEnvToCek? m ρ = some env)
    (hρno : symEnvNoOpaqueForSoundness ρ = true)
    (hno : termNoOpaqueBuiltinsForSoundness t)
    (hrhs : SmtSem.eval m rhs = some (.int expected))
    (hcond : SmtSem.evalBoolIs m
      (Moist.SMT.Expr.simplifyBool
        (okIntEqCond (evalSym fuel ρ t) rhs)) true = true) :
    bigEval fuel env t = some (.VCon (.Integer expected)) := by
  apply evalSym_okIntEqCond_bigEval henv hρno hno hrhs
  simpa only [Moist.SMT.Semantics.evalBoolIs_simplifyBool] using hcond

end Moist.SMT.UPLC.Soundness
